kind: Deployment
apiVersion: app/v1
metadata:
   name: mysql
   namespace: expense
   # these labels are deployment related labels.
   labels: 
     component: nginx
     project: expense
     tier: database
   spec:
     replicas: 2
     selector:
        matchLabels:
          component: nginx
          project: expense
          tier: database
    # pod defination
template:
  metadata: 
    Labels:
      component: nginx
      project: expense
      tier: database
  spec:
   containers:
   - name: mysql
     image: joindevops/mysql:v1.0

---

apiversion: v1
kind: service
metadata: 
 name: nginx
spec: 
 selector:
      name: front-end
      project: expense
      component: frontend
      environment: dev
ports:
    - protocol: TCP
      port: 3306  #service-port
      targetport: 3306 #target-port